

Verb_ending_in_ing = input("Enter Verb Ending In ing: ")
Type_of_liquid = input("Enter Type of liquid: ")
type_of_food = input("Enter Type of Food: ")
adjective1 = input("Enter Adjective: ")
noun1 = input("Enter Noun: ")
Adverb1 = input("Enter Adverb: ")
noun2 = input("Enter Noun: ")
adjective2 = input("Enter Adjective: ")
verb1 = input("Enter Verb: ")
Adverb2 = input("Enter Adverb: ")
Plural_noun1 = input("Enter Plural Noun: ")
Plural_noun2 = input("Enter Plural Noun: ")
Part_of_the_body = input("Enter Part of the body: ")
Plural_noun3 = input("Enter Plural Noun: ")
adjective3 = input("Enter Adjective: ")
Name = input("Enter Name of a Male: ")
Exclamation = input("Enter Exclamation: ")
A_place = input("Enter a place: ")


print('After ' + '\33[4m',Verb_ending_in_ing + '\33[m',' shotguns at the range, drinking ' + '\33[4m',Type_of_liquid )
print('\33[m','by the pool, and a big ' + '\33[4m',type_of_food + '\33[m',' dinner, this is turning' )
print('out to be a/an ' +'\33[4m',adjective1 + '\33[m',' night. I\'m at some bar called the ')
print('\33[4m',noun1+ '\33[m',' Lounge, and I am ' + '\33[4m',Adverb1 + '\33[m',' Smashed right now.')
print('We have ' + '\33[4m',noun2 + '\33[m',' service in a/an ' + '\33[4m',adjective2 + '\33[m',' VIP area,')
print('but there are no girls here. Well, I\'m the groom, so i think i\'ll go')
print('\33[4m',verb1 + '\33[m',' some up. I Can\'t ' + '\33[4m',Adverb2 + '\33[m',' see anything with all')
print('the flashing ' + '\33[4m',Plural_noun1 + '\33[m',' in this club, but i think there\'s a group')
print('of ' + '\33[4m',Plural_noun2 + '\33[m',' in that corner. Hmmm...there\'s a brunette')
print('over there...I can\'t see her face, but boy does she have a great')
print('\33[4m',Part_of_the_body + '\33[m','. I\'ll ask her if she and her friends want to join us for')
print('a round of ' + '\33[4m',Plural_noun3 + '\33[m','. \"Excuse me, but we have ' + '\33[4m',adjective3)
print('\33[m','booze and no one to share it with. Want to join us?\" I say. She turns')
print('\33[m','around and smiles at me. \"Yes, ' + '\33[4m',Name + '\33[m',', we\'d love to join')
print('you,\" she says ' + '\33[4m',Exclamation + '\33[m','! I must be the only groom in (the)')
print('\33[4m',A_place + '\33[m',' to hit on his own fiancée during his bachelor party.')  

#This is Madlibs game created by Prabin Bastakoti.